export const ALGORITHMS = {
  bubble:    { name: 'Bubble Sort',    big_o: 'O(n²)',       space: 'O(1)',      desc: 'Compares adjacent elements and swaps them if out of order. Repeats until no swaps occur.' },
  selection: { name: 'Selection Sort', big_o: 'O(n²)',       space: 'O(1)',      desc: 'Finds the minimum element from the unsorted portion and places it at the beginning.' },
  insertion: { name: 'Insertion Sort', big_o: 'O(n²)',       space: 'O(1)',      desc: 'Builds the sorted array one element at a time by inserting each into its correct position.' },
  merge:     { name: 'Merge Sort',     big_o: 'O(n log n)',  space: 'O(n)',      desc: 'Recursively divides the array in half, sorts each half, then merges them back together.' },
  quick:     { name: 'Quick Sort',     big_o: 'O(n log n)*', space: 'O(log n)', desc: 'Picks a pivot, partitions the array around it, then recursively sorts each partition.' },
  heap:      { name: 'Heap Sort',      big_o: 'O(n log n)',  space: 'O(1)',      desc: 'Converts the array into a max heap, then repeatedly extracts the maximum element.' },
  shell:     { name: 'Shell Sort',     big_o: 'O(n log²n)',  space: 'O(1)',      desc: 'An optimization of insertion sort that compares elements far apart, then reduces the gap.' },
  cocktail:  { name: 'Cocktail Sort',  big_o: 'O(n²)',       space: 'O(1)',      desc: 'A bidirectional bubble sort that sorts in both directions each pass.' },
  comb:      { name: 'Comb Sort',      big_o: 'O(n log n)',  space: 'O(1)',      desc: 'Improves on bubble sort by using a gap to eliminate "turtles" (small values at the end).' },
  gnome:     { name: 'Gnome Sort',     big_o: 'O(n²)',       space: 'O(1)',      desc: 'Similar to insertion sort, but moves an element to its place by a series of swaps.' },
  oddeven:   { name: 'Odd-Even Sort',  big_o: 'O(n²)',       space: 'O(1)',      desc: 'A parallel version of bubble sort that compares odd/even indexed pairs.' },
  pancake:   { name: 'Pancake Sort',   big_o: 'O(n²)',       space: 'O(1)',      desc: 'Sorts by flipping the prefix of the array to move the largest element to the end.' },
  cycle:     { name: 'Cycle Sort',     big_o: 'O(n²)',       space: 'O(1)',      desc: 'An in-place sorting algorithm that minimizes the number of writes to the array.' },
  radix:     { name: 'Radix Sort',     big_o: 'O(nk)',       space: 'O(n+k)',    desc: 'A non-comparative sort that distributes elements into buckets based on their digits.' },
  capitalist:{ name: 'Capitalist Sort',big_o: 'O(n)',        space: 'O(1)',      desc: 'The 1% absorbs most of the wealth, leaving the other elements with a meager minimum wage.' },
  communist: { name: 'Communist Sort', big_o: 'O(n)',        space: 'O(1)',      desc: 'Redistributes the values equally among all elements. Everyone gets the exact same value.' },
  tim:       { name: 'Tim Sort',       big_o: 'O(n log n)',  space: 'O(n)',      desc: 'A hybrid derived from merge and insertion sort. It sorts small blocks and merges them.' },
  bogo:      { name: 'Bogo Sort',      big_o: 'O(n · n!)',   space: 'O(1)',      desc: 'Repeatedly shuffles the array until it magically becomes sorted. Extremely inefficient.' },
  stalin:    { name: 'Stalin Sort',    big_o: 'O(n)',        space: 'O(1)',      desc: 'Eliminates any element that is out of order. Results in a sorted but potentially much smaller array.' },
  stooge:    { name: 'Stooge Sort',    big_o: 'O(n^2.709)',  space: 'O(log n)',  desc: 'A recursive sorting algorithm that sorts the first 2/3, then the last 2/3, then the first 2/3 again.' },
  quantum:   { name: 'Quantum Bogo',   big_o: 'O(1)',        space: 'O(1)',      desc: 'Destroys every universe where the array is not sorted. In this universe, it is sorted instantly.' },
  slow:      { name: 'Slow Sort',      big_o: 'O(n^log n)',  space: 'O(log n)',  desc: 'A multiply-and-surrender algorithm that is designed to be as slow as possible while still sorting.' },
  coin:      { name: 'Coin Flip Sort', big_o: 'O(n²)?',      space: 'O(1)',      desc: 'A probabilistic bubble sort. Every potential swap is decided by a literal coin flip.' },
  existential:{ name: 'Existential Sort',big_o: '∞',           space: 'O(1)',      desc: 'A poorly implemented algorithm that questions its own logic and never actually finishes.' },
  frustration:{ name: 'Frustration Sort', big_o: '∞',           space: 'O(1)',      desc: 'Nearly sorts the array, then loses its temper and shuffles everything back to chaos.' },
  crash:     { name: 'Crash Sort',       big_o: 'O(???)',      space: 'O(crash)',  desc: 'A realistically poor implementation that simply gives up and crashes halfway through.' },
};

export const PRESETS = {
  random:   'Random',
  reversed: 'Reversed',
  nearly:   'Nearly Sorted',
  unique:   'Few Unique',
  sorted:   'Already Sorted',
  mountain: 'Mountain',
  valley:   'Valley',
  sawtooth: 'Sawtooth',
};
