export const FERMI_QUESTIONS = [
  { q: "How many standard golf balls could fit inside a typical school bus?", ans: 6, desc: "A school bus is ~35 m³, a golf ball is ~40 cm³. With ~70% packing, it is ~600,000 to 1,000,000 golf balls (10⁶)." },
  { q: "How many piano tuners are actively working in Chicago?", ans: 2, desc: "Population ~3M, ~1% households tune pianos annually, yielding roughly 150 to 300 active tuners (10²)." },
  { q: "How many heartbeats does a human make in an 80-year lifetime?", ans: 9, desc: "At ~75 beats per minute, a human heart beats approximately 3 billion times in 80 years (10⁹)." },
  { q: "How many seconds are in a single calendar year?", ans: 7, desc: "60 * 60 * 24 * 365 = 31,536,000 seconds (10⁷)." },
  { q: "How many grains of sand are there on all the beaches on Earth?", ans: 18, desc: "Estimated by geologists to be around 7.5 x 10¹⁸ grains." },
  { q: "How many breaths does a typical person take in a lifetime?", ans: 9, desc: "At ~16 breaths per minute, a person takes ~6.7 x 10⁸ breaths in 80 years (10⁹)." },
  { q: "How many miles are in a single light-year?", ans: 13, desc: "Light travels at 186,000 miles/sec, totaling ~5.88 trillion miles in a year (10¹³)." },
  { q: "How many individual cells are in a typical adult human body?", ans: 13, desc: "Estimated by biologists to be around 30 trillion cells (10¹³)." },
  { q: "How many hairs are on a typical human head?", ans: 5, desc: "Humans have an average of 100,000 hair follicles on their head (10⁵)." },
  { q: "How many minutes does it take for light from the Sun to reach Earth?", ans: 1, desc: "Light takes ~8.3 minutes to travel from the Sun to Earth (10¹)." },
  { q: "How many gallons of water are in an Olympic-sized swimming pool?", ans: 6, desc: "An Olympic pool holds ~660,000 US gallons (10⁶)." },
  { q: "How many people are currently alive on Earth?", ans: 10, desc: "The global population passed 8 billion in late 2022 (10¹⁰)." },
  { q: "How many sheets of paper in a stack as tall as the Empire State Building?", ans: 6, desc: "At ~0.1mm per sheet, a 381m building corresponds to ~3.8 million sheets (10⁶)." },
  { q: "How many drops of water are in a single liter?", ans: 4, desc: "A standard drop of water is ~0.05 mL, yielding ~20,000 drops per liter (10⁴)." },
  { q: "How many planet Earths could fit inside the Sun?", ans: 6, desc: "The volume of the Sun is ~1.3 million times larger than Earth (10⁶)." },
  { q: "How many seconds does it take for light to travel across the United States?", ans: -2, desc: "Light traverses the US width (~4800 km) in ~0.016 seconds (10⁻²)." },
  { q: "How many base pairs are there in the human genome?", ans: 9, desc: "The haploid human genome contains ~3.2 billion base pairs (10⁹)." },
  { q: "How many dollar bills placed end-to-end would reach the Moon?", ans: 9, desc: "A bill is ~15.6 cm; reaching the Moon (~384,400 km) takes ~2.46 billion bills (10⁹)." },
  { q: "How many letters are in the entire Harry Potter book series?", ans: 7, desc: "The series contains ~1 million words, totaling ~6 million characters (10⁷)." },
  { q: "How many standard bricks are needed to build a two-story house?", ans: 4, desc: "A standard two-story brick house takes roughly 15,000 to 20,000 bricks (10⁴)." },
  { q: "How many air molecules are inside a typical university lecture hall?", ans: 28, desc: "Based on molar volume of a gas at room temp, there are ~8.00e+27 molecules (10²⁸)." },
  { q: "How many ants would fit inside The Shard in London?", ans: 16, desc: "Given the building volume and packing efficiency, it fits ~9.70e+15 ants (10¹⁶)." },
  { q: "What is the surface area of the Earth in square miles?", ans: 8, desc: "The Earth has a radius of ~3,959 miles, yielding ~197 million square miles (10⁸)." },
  { q: "What is the ratio of the energy of a major tsunami to a standard atomic bomb?", ans: 6, desc: "A massive tsunami outputs ~10¹⁶ Joules; an atomic bomb outputs ~10¹⁰ Joules (10⁶)." },
  { q: "How many times would a car's wheels rotate if driven around the equator of the Earth?", ans: 8, desc: "Equator circumference is ~40,075 km; a standard wheel rotates ~1.80e+08 times (10⁸)." },
  { q: "How many Mars bars lined up end-to-end would reach from London to Birmingham?", ans: 6, desc: "A Mars bar is ~10cm; London to Birmingham (~160km) takes ~1.68 million bars (10⁶)." },
  { q: "How many 'conversations' are active in Reddit comment sections at any given time?", ans: 6, desc: "Reddit comment sections hold roughly 500,000 active discussion trees (10⁶)." },
  { q: "How many pennies stacked together equal the height of the Burj Khalifa?", ans: 6, desc: "At 1.52mm thickness, matching the Burj Khalifa's 828m takes ~552,000 pennies (10⁶)." },
  { q: "How many hot dogs are purchased at all Major League Baseball games in a single season?", ans: 6, desc: "Across all games and concessions, fans buy ~1.13 million hot dogs per season (10⁶)." },
  { q: "How many standard $1 coins could you fit inside a typical large suitcase?", ans: 4, desc: "Accounting for packing density, a standard suitcase fits ~19,700 coins (10⁴)." },
  { q: "How many swimming pools could be filled by all the blood donated each year in the US?", ans: 2, desc: "Annual donations yield ~7.3M liters, which fills roughly 68 Olympic swimming pools (10²)." },
  { q: "What is the estimated number of Deliveroo drivers active in London?", ans: 5, desc: "The gig economy service utilizes roughly 250,000 active riders in London (10⁵)." },
  { q: "How many liters of water does an average household consume each week?", ans: 4, desc: "An average household consumes ~3,500 liters of water weekly (10⁴)." },
  { q: "What is the total mass in kilograms of all gasoline a typical car consumes in its lifetime?", ans: 4, desc: "Assuming a lifespan of 150k miles, a car consumes ~23,800 kg of gasoline (10⁴)." },
  { q: "How many coins have been minted in all of human history?", ans: 12, desc: "Historians estimate total global coin mintings at ~3 trillion coins (10¹²)." },
  { q: "How many hours would a year be if the Earth orbited the sun at 100 km/s?", ans: 3, desc: "Orbital period at this speed translates to roughly 3,650 hours in a year (10³)." },
  { q: "What is the volume in cubic centimeters (cc) of blood in a healthy newborn baby?", ans: 2, desc: "A healthy newborn baby has approximately 75 to 80 cc of blood (10²)." },
  { q: "What is the total energy in Joules needed to completely evaporate all Earth's oceans?", ans: 27, desc: "Latent heat of vaporization of ocean water is ~7.00e+26 Joules (10²⁷)." },
  { q: "How many port-a-potties are recommended to be planned for a march of one million people?", ans: 4, desc: "Planning guidelines suggest ~20,000 toilets for a gathering of this scale (10⁴)." },
  { q: "What is the energy in electron volts (eV) of the most energetic cosmic gamma-ray photon detected by NASA's Fermi Telescope?", ans: 11, desc: "NASA's Fermi LAT has detected photons with energies exceeding 300 billion electron volts (3 x 10¹¹ eV)." },
  { q: "How many active astrophysical sources (blazars, pulsars) were cataloged in NASA's Fermi Third Point Source Catalog?", ans: 3, desc: "The 3FGL catalog contains 3,033 high-energy gamma-ray sources (10³)." },
  { q: "How many kilograms does the Fermi Gamma-ray Space Telescope spacecraft weigh?", ans: 3, desc: "The spacecraft has a mass of approximately 4,303 kilograms (10³)." },
  { q: "How many miles above the Earth is the low Earth orbit of NASA's Fermi Space Telescope?", ans: 2, desc: "Fermi orbits at an altitude of approximately 350 miles or 560 kilometers (10²)." },
  { q: "How many seconds does it take for NASA's Fermi Telescope to scan the entire sky in standard survey mode?", ans: 4, desc: "Fermi scans the entire sky every two orbits, which takes about 3 hours or 10,800 seconds (10⁴)." },
  { q: "How many transient Gamma-ray Bursts (GRBs) does the NASA Fermi GBM instrument detect annually?", ans: 2, desc: "The Gamma-ray Burst Monitor detects about 250 to 300 cosmic bursts each year (10²)." },
  { q: "How many nanoseconds did it take you to read a typical short sentence?", ans: 9, desc: "Reading a short sentence takes about 1 second, which is equal to 1,000,000,000 nanoseconds (10⁹)." },
  { q: "How many years would it take to walk from San Francisco to New York at standard walking speed?", ans: -1, desc: "A cross-country walk takes ~1.2 months, which is approximately 0.1 years (10⁻¹)." },
  { q: "How many ways can 15 unique books be arranged on a three-shelf bookcase, assuming 5 books per shelf?", ans: 12, desc: "The number of arrangements is 15!, which is equal to 1,307,674,368,000 (10¹²)." },
  { q: "How many atoms of gold are in one carat of pure 24-karat gold?", ans: 21, desc: "One carat is 0.2 grams. With gold's molar mass, this corresponds to ~6.1 x 10²¹ atoms." },
  { q: "How many standard helium balloons are required to lift a typical human being?", ans: 4, desc: "A standard balloon lifts ~14 grams. Lifting an 80kg human takes roughly 5,700 balloons (10⁴)." },
  { q: "How many atoms of gold are coated onto the mirrors of the James Webb Space Telescope?", ans: 23, desc: "The JWST mirrors are coated with 48 grams of gold, which corresponds to ~1.46 x 10²³ atoms." },
  { q: "What is the probability of a person having a negative IQ, assuming a normal distribution centered at 100?", ans: -11, desc: "Negative IQ is over 6.6 standard deviations below the mean, yielding a probability of ~10⁻¹¹." },
  { q: "How many 500-mL bottles of water are needed to cover Bangladesh in 1 cm of standing water?", ans: 12, desc: "Bangladesh area is ~1.47e11 m². Cover in 1cm takes ~1.47e9 m³ = 2.9e12 bottles (10¹²)." },
  { q: "How many practicing orthodontists are in the state of Iowa?", ans: 2, desc: "Based on dental registries, there are roughly 100 to 150 active orthodontists in Iowa (10²)." },
  { q: "How many miles of interstate highways are there in the United States?", ans: 4, desc: "The US interstate highway system spans approximately 48,000 miles (10⁴)." },
  { q: "How many Sverdrups (flow unit) is the entire global river fresh water input to the oceans?", ans: 0, desc: "Global river discharge is ~1.2 million m³/s, which is equal to 1.2 Sverdrups (10⁰)." },
  { q: "How many millimeters are in a single kilometer?", ans: 6, desc: "1 km = 1,000 m = 1,000,000 mm (10⁶)." },
  { q: "How many seconds are in a single decade?", ans: 8, desc: "10 years = 3,652 days = 315,576,000 seconds (10⁸)." },
  { q: "How many bird species have been officially recorded in the state of California?", ans: 3, desc: "California has recorded 681 distinct species of birds as of recent counts (10³)." }
];
